### ISSUE TITLE
panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync#42]
I just received this error after some 20mins of ouisync running: 

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', lib/src/network/mod.rs:546:59
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/option.rs:746:21
   4: ouisync::network::Inner::keep_connecting::{{closure}}
             at ./lib/src/network/mod.rs:546:36
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
   6: ouisync::network::Inner::establish_dht_connection::{{closure}}
             at ./lib/src/network/mod.rs:526:22
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
   8: ouisync::scoped_task::ScopedTaskSetHandle::spawn::{{closure}}
             at ./lib/src/scoped_task.rs:50:17
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/future.rs:119:9
  11: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/core.rs:161:17
  12: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/loom/std/unsafe_cell.rs:14:9
  13: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/core.rs:151:13
  14: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/harness.rs:467:19
  15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panic/unwind_safe.rs:271:9
  16: std::panicking::try::do_call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  17: __rust_try
  18: std::panicking::try
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  19: std::panic::catch_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  20: tokio::runtime::task::harness::poll_future
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/harness.rs:455:18
  21: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/harness.rs:103:27
  22: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/harness.rs:57:15
  23: tokio::runtime::task::raw::poll
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/raw.rs:144:5
  24: tokio::runtime::task::raw::RawTask::poll
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/raw.rs:84:18
  25: tokio::runtime::task::LocalNotified<S>::run
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/mod.rs:354:9
  26: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/thread_pool/worker.rs:427:13
  27: tokio::coop::with_budget::{{closure}}
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/coop.rs:102:9
  28: std::thread::local::LocalKey<T>::try_with
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
  29: std::thread::local::LocalKey<T>::with
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  30: tokio::coop::with_budget
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/coop.rs:95:5
  31: tokio::coop::budget
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/coop.rs:72:5
  32: tokio::runtime::thread_pool::worker::Context::run_task
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/thread_pool/worker.rs:426:9
  33: tokio::runtime::thread_pool::worker::Context::run
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/thread_pool/worker.rs:393:24
  34: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/thread_pool/worker.rs:378:17
  35: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/macros/scoped_tls.rs:61:9
  36: tokio::runtime::thread_pool::worker::run
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/thread_pool/worker.rs:375:5
  37: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/thread_pool/worker.rs:354:45
  38: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/blocking/task.rs:42:21
  39: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/core.rs:161:17
  40: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/loom/std/unsafe_cell.rs:14:9
  41: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/core.rs:151:13
  42: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/harness.rs:467:19
  43: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panic/unwind_safe.rs:271:9
  44: std::panicking::try::do_call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
  45: __rust_try
  46: std::panicking::try
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
  47: std::panic::catch_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
  48: tokio::runtime::task::harness::poll_future
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/harness.rs:455:18
  49: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/harness.rs:103:27
  50: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/harness.rs:57:15
  51: tokio::runtime::task::raw::poll
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/raw.rs:144:5
  52: tokio::runtime::task::raw::RawTask::poll
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/raw.rs:84:18
  53: tokio::runtime::task::UnownedTask<S>::run
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/task/mod.rs:391:9
  54: tokio::runtime::blocking::pool::Task::run
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/blocking/pool.rs:91:9
  55: tokio::runtime::blocking::pool::Inner::run
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/blocking/pool.rs:324:17
  56: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/peter/.cargo/git/checkouts/tokio-377c595163f99a10/83477c7/tokio/src/runtime/blocking/pool.rs:299:13
```

Commit 89ba6b4c968b

**Comment by inetic** [comment]
Should now be fixed by https://github.com/equalitie/ouisync/commit/d20e1dd466344b169be7062d7f52f6f5e0b4829f
