### ISSUE TITLE
Assertion when moving files

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync#68]
This happened when I was testing on PC and Android. I started fresh on PC and sent the token to Android. Then I

1. On PC I copied a 4MB large file to the mounted root
2. On Android I create a directory `/dir`
3. On Android I moved the 4MB large file into `/dir`
4. The crash happened on PC

```
thread 'tokio-runtime-worker' panicked at 'assertion failed: !path.has_leaf(block_id)', lib/src/index/branch_data.rs:116:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:48:5
   3: ouisync::index::branch_data::BranchData::insert::{{closure}}
             at ./lib/src/index/branch_data.rs:116:9
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   5: ouisync::blob::Blob::try_fork::{{closure}}
             at ./lib/src/blob/mod.rs:170:69
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   7: ouisync::directory::parent_context::ParentContext::fork::{{closure}}
             at ./lib/src/directory/parent_context.rs:70:64
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   9: ouisync::file::File::fork::{{closure}}
             at ./lib/src/file.rs:152:69
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  11: ouisync::joint_directory::JointDirectory::merge::{{closure}}
             at ./lib/src/joint_directory/mod.rs:288:81
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
  14: ouisync::joint_directory::JointDirectory::merge::{{closure}}
             at ./lib/src/joint_directory/mod.rs:306:46
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  16: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
  17: ouisync::repository::worker::merge::run::{{closure}}::{{closure}}::{{closure}}
             at ./lib/src/repository/worker.rs:207:38
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  19: ouisync::repository::worker::merge::run::{{closure}}::{{closure}}
             at ./lib/src/repository/worker.rs:192:83
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  21: ouisync::repository::worker::merge::run::{{closure}}
             at ./lib/src/repository/worker.rs:191:5
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  23: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/task/task_local.rs:280:28
  24: tokio::task::task_local::TaskLocalFuture<T,F>::with_task
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/task/task_local.rs:272:9
  25: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/task/task_local.rs:280:9
  26: ouisync::event::EventScope::apply::{{closure}}
             at ./lib/src/event.rs:57:37
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  28: ouisync::repository::worker::Inner::merge::{{closure}}
             at ./lib/src/repository/worker.rs:164:59
  29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  30: ouisync::repository::worker::Inner::run::{{closure}}::{{closure}}
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/macros/select.rs:507:49
  31: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/future/poll_fn.rs:38:9
  32: ouisync::repository::worker::Inner::run::{{closure}}
             at ./lib/src/repository/worker.rs:128:13
  33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  34: ouisync::repository::worker::Worker::run::{{closure}}::{{closure}}
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/macros/select.rs:507:49
  35: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/future/poll_fn.rs:38:9
  36: ouisync::repository::worker::Worker::run::{{closure}}
             at ./lib/src/repository/worker.rs:51:9
  37: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  38: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.35/src/instrument.rs:272:9
  39: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
  40: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:165:17
  41: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/loom/std/unsafe_cell.rs:14:9
  42: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:155:13
  43: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:470:19
  44: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panic/unwind_safe.rs:271:9
  45: std::panicking::try::do_call
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  46: __rust_try
  47: std::panicking::try
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  48: std::panic::catch_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  49: tokio::runtime::task::harness::poll_future
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:458:18
  50: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:104:27
  51: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:57:15
  52: tokio::runtime::task::raw::poll
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:144:5
  53: tokio::runtime::task::raw::RawTask::poll
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:84:18
  54: tokio::runtime::task::LocalNotified<S>::run
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/mod.rs:376:9
  55: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:435:13
  56: tokio::coop::with_budget::{{closure}}
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  57: std::thread::local::LocalKey<T>::try_with
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:442:16
  58: std::thread::local::LocalKey<T>::with
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:418:9
  59: tokio::coop::with_budget
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  60: tokio::coop::budget
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  61: tokio::runtime::thread_pool::worker::Context::run_task
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:434:9
  62: tokio::runtime::thread_pool::worker::Context::run
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:401:24
  63: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:386:17
  64: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/macros/scoped_tls.rs:61:9
  65: tokio::runtime::thread_pool::worker::run
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:383:5
  66: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:362:45
  67: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/task.rs:42:21
  68: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:165:17
  69: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/loom/std/unsafe_cell.rs:14:9
  70: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:155:13
  71: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:470:19
  72: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panic/unwind_safe.rs:271:9
  73: std::panicking::try::do_call
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
  74: __rust_try
  75: std::panicking::try
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
  76: std::panic::catch_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
  77: tokio::runtime::task::harness::poll_future
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:458:18
  78: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:104:27
  79: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:57:15
  80: tokio::runtime::task::raw::poll
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:144:5
  81: tokio::runtime::task::raw::RawTask::poll
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:84:18
  82: tokio::runtime::task::UnownedTask<S>::run
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/mod.rs:413:9
  83: tokio::runtime::blocking::pool::Task::run
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:91:9
  84: tokio::runtime::blocking::pool::Inner::run
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:325:17
  85: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:300:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  2022-08-05T06:58:22.764786Z DEBUG  sync progress: 4161536/4161536 bytes (100.0%), repo: 0
    at lib/src/repository/mod.rs:751
```

**Comment by inetic** [comment]
Implemented a fix in https://github.com/equalitie/ouisync/commit/573af8d37e697fd2ae20f38c02d72f2575d1861a , but keeping this issue open to discuss it.

**Comment by madadam** [comment]
Fix in https://github.com/equalitie/ouisync/commit/573af8d37e697fd2ae20f38c02d72f2575d1861a is sufficient for this, but see #70 for a followup. Closing.
